apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: appd-cluster-agent
spec: 
  replicas: 1
  template: 
    metadata: 
      annotations: 
        appd-agent-id: appdynamics-cluster-agent
      labels: 
        name: cluster-agent
    restartPolicy: Always
    spec: 
      containers: 
        - env: 
            - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
              valueFrom: 
                secretKeyRef: 
                  key: controller-key
                  name: cluster-agent-secret
            - name: APPDYNAMICS_EVENT_ACCESS_KEY
              valueFrom: 
                secretKeyRef: 
                  key: event-key
                  name: cluster-agent-secret
            - name: APPDYNAMICS_REST_API_CREDENTIALS
              valueFrom: 
                secretKeyRef: 
                  key: api-user
                  name: cluster-agent-secret
            - name: APPDYNAMICS_AGENT_NAMESPACE
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.namespace
          image: "sashaz/cluster-agent@sha256:34344aaa02eb09c5c6fb02f00e2178025769392dccfc8d2ec3977b2d44de12d1"
          imagePullPolicy: IfNotPresent
          name: cluster-agent
          ports: 
            - containerPort: 8989
              protocol: TCP
          resources: 
            limits: 
              cpu: 200m
              memory: 300M
            requests: 
              cpu: 100m
              memory: 100M
          volumeMounts: 
            - mountPath: /opt/appdynamics/config/
              name: agent-config
      serviceAccountName: appdynamics-operator
      volumes: 
        - configMap: 
            name: cluster-agent-config
          name: agent-config
