kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appdynamics-operator
subjects:
- kind: ServiceAccount
  name: appdynamics-operator
  namespace: appdynamics-infra
roleRef:
  kind: ClusterRole
  name: appdynamics-operator
  apiGroup: rbac.authorization.k8s.io
