apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appd-cluster-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cluster-agent
    spec:
      serviceAccountName: appdynamics-operator
      containers:
      - name: cluster-agent
        image: appdynamics/cluster-agent:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: cluster-agent-config
        env:
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: controller-key
              name: cluster-agent-secret
        - name: APPDYNAMICS_EVENT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: event-key
              name: cluster-agent-secret
        - name: APPDYNAMICS_REST_API_CREDENTIALS
          valueFrom:
            secretKeyRef:
              key: api-user
              name: cluster-agent-secret
		- name: APPDYNAMICS_AGENT_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
		volumeMounts:
        - name: agent-config
          mountPath: /opt/appdynamics/config/
        ports:
        - containerPort: 8989
          protocol: TCP
	volumes:
      - name: agent-config
        configMap:
          name: cluster-agent-config
    restartPolicy: Always