apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
spec:
  selector:
    matchLabels:
      k8s-app: metrics-server
  template:
    metadata:
      name: metrics-server
      labels:
        k8s-app: metrics-server
    spec:
      serviceAccountName: metrics-server
      volumes:
      # mount in tmp so we can safely use from-scratch images and/or read-only containers
      - name: tmp-dir
        emptyDir: {}
      - name: certs
        secret: 
          secretName: cluster-certs
      containers:
      - name: metrics-server
        image: k8s.gcr.io/metrics-server-amd64:v0.3.1
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0 
        command: [/metrics-server, --kubelet-insecure-tls, --cert-dir="/var/run/kubernetes"] 
        volumeMounts:
        - name: tmp-dir
          mountPath: /tmp
        - name: certs
          mountPath: /var/run/kubernetes
